### ISSUE TITLE
jei overrides not working

### ISSUE THREAD

**Issue by keramond** [elix-x/Forever-Enough-Items#19]
hey iam using the mod on a 1.9.4 mp server and the overrides dont apply when switching profiles, i have to reset the option in the profile manager everytime.

**Comment by Elix-x** [comment]
A few specific options or is it the case for all of them?

**Comment by keramond** [comment]
give items, delete items and center search, so should be all of them

**Comment by Elix-x** [comment]
And what specifically happens?
Which version of JEI are you using?

**Comment by keramond** [comment]
jei 1.9.4 2.6.2.211

so i want the cheat mode profile to be able to cheat in items from the item list, and the recipe profile to show the recipe instead. but it just uses the give item option i last set in the profile manager, not considering which profile i have curently active.

**Comment by Elix-x** [comment]
Ok, that's even weirder...
Can you try with jei_1.9.4-3.4.0.204?

**Comment by dioticdrone** [comment]
I think this has regressed. I'm experiencing this in 1.10.2 with FEI 1.0.15, JEI 3.7.8.234, or was never fixed for 1.10.2.

**Comment by Elix-x** [comment]
So, search bar isn't centered and other stuff like that?
Check that FEI loads in general, you have latest excore (which if you wouldn't have should have crashed badly - #33).
If that didn't help, i'll look into this as soon as i get workspace re-set-up.

**Comment by dioticdrone** [comment]
The search bar IS centered and the top left buttons (rain, time, overlays) all work, but changing the mode (cheat/util/recipe) doesn't change JEI cheat mode so clicking an item in JEI will still show the recipe instead of cheating in a stack even when I change to cheat mode. This may be a little different than what the OP was describing, especially since I'm trying to get my pack to work locally before moving it to my server.

I noticed that the current.profile file in the config folder still says "Recipe Mode" when I change to cheat mode. I don't know if that is what you use to store what mode you're in, but it's not getting updated if you are.

I installed FEI and Excore late last night, so I assume I have the latest version. I'm not going to check.

I apologize if I'm just being dumb. I'm extremely tired.

**Comment by Elix-x** [comment]
Tried `/feiop`?

**Comment by dioticdrone** [comment]
Yeah. I found that command on the curse page when I first realized I couldn't cheat in items in cheat mode, the first time I installed FEI.

Upon further investigation: Changing the mode only gets changed (with regard to cheating in items from JEI) if you log out and back in to the world. The other functions like changing weather and time work fine when you change to cheat mode.

Sorry if this seems insignificant. the jei mode button and creative mode buttons are the whole reason I want to use FEI. I have a private server for me and a friend and I have to do a lot of (cheaty) maintenance since all the 1.10.2 mods are super buggy right now, and want a convenient way to do this other than having to type /gamemode blah and going into the JEI options to enable cheating.

**Comment by Elix-x** [comment]
> Upon further investigation: Changing the mode only gets changed (with regard to cheating in items from JEI) if you log out and back in to the world.

This is very important, what you said here. I now know ~exactly what's the reason and what to do. Thanks.

**Comment by dioticdrone** [comment]
Glad I could help.

**Comment by Neuron67** [comment]
Everything working except the search bar. 
Have the latest excore and JEI installed but search does nothing.
I've followed every link and read every word on every issue but haven't found a solution.
Anybody know how to fix?

**Comment by Elix-x** [comment]
@Neuron67 Minecraft 1.11.2? If yes, please create a new issue.
