### ISSUE TITLE
GUI shows not proper eventually Problem with JEI

### ISSUE THREAD

**Issue by ghost** [elix-x/Forever-Enough-Items#2]
sorry but i found another Problem. 
I believe it's JEI. I have found an entry in the log file. the Games is not crashing just the GUI shows not all buttons correctly and some of them are not available. 

Screenshot here: https://imgur.com/a/phfS3. 
log file (Game is running): http://paste.ee/p/jG5Vx 

You sayed you will be informed if that happens.
I'll open it in JEI repository also.
best regards jokish

**Comment by Elix-x** [comment]
Wih buttons are you speaking of?
If speak about JEI settings button,

> You may also notice that wrench icon in bottom right corner is gone. THat's because JEI is now configured per profile.

Also, (because item subsets covers left arrow) adjust your elements positions (resize mc screen vertically, untill you see profiles button in bottom left corner appear. Right click on it to change profiles settings. From, there, in position and size screen, use your numpad to center elements correctly).

**Comment by ghost** [comment]
I speak from the yellow apple button. It take me a while to figure it out what is left- or right-click. 
(I'm not really good in reading english text).
The only thing is left: After a change from the GUI scale in the Video Settings this button is moving upwards. All other things does not change their positions.
From my perspective, the menus are a bit confusing.
Example: I think it would be good if I could see all the elements together during adjustment.
the JEI Problems in the log already occur. I will report that in the JEI Repository.
thank you for helping so fast.
best regards jokish

**Comment by Elix-x** [comment]
Other things do not change their position, because a) they're at 0 height b) they are hardcoded to be where they are.

Left clicking lets you select between profiles, right clicking, manage your profiles, and settings of elements.

I would like it too, but i don't think it is easily doable. But i'll look into it.
