### ISSUE TITLE
Please set a maximum supported JEI version on all releases

### ISSUE THREAD

**Issue by mezz** [elix-x/Forever-Enough-Items#26]
I am getting reports any time I update JEI because FEI is messing with internal classes.

At the very least, please set the version range on your JEI dependency so that it is something like
`required-after:JEI@[3.7.0,3.7.1];`
This way when JEI updates, players will get a warning that FEI only supports up to version 3.7.1 instead of having it crash.

**Comment by Elix-x** [comment]
While i'm trying to always check changes in your repository, i can't always apply changes to FEI right after you applied to JEI. I could set maximum version, but still your internal classes that FEI depends on do not change on each release. And if i would limit it, i would have to update FEI each time you post a new release just with changed max version.

Unless, you have a version number that is incremented only when specific classes change (like second number in forge's version). If so, i would like to know which one so i could use it to range FEI's JEI dependency in between 2 changes that would otherwise break it (before and after).

By the way, i know that a lot of people with FEI crashes come to you. Even though i warned them multiple times. There's a warning in big bold red on FEI's curse page concerning crashes. It seems that nobody reads it.

**Comment by mezz** [comment]
That is the nature of this project, it is your choice to do it this way. I support an API with versioning already, I do not support using or altering my internal classes. If you want to be responsible about it please set a maximum version. [I have even improved the missing mods screen with this type of situation in mind, so players are not confused.](https://github.com/MinecraftForge/MinecraftForge/pull/2997) People will be clearly informed that they should downgrade JEI to be able to play, instead of having their game broken and coming to me saying it crashes.

**Comment by Elix-x** [comment]
I saw your PR already, partially guessing where it came from.
I'll see what i can do about it (method existence checks). In the worst case, i will simply set maximum version.

**Comment by mezz** [comment]
Thank you!
