### ISSUE TITLE
Error when searching for items in the search bar 

### ISSUE THREAD

**Issue by DatrixTHLK** [elix-x/Forever-Enough-Items#56]
Hello,

If you knew of this already, then you may close the issue and I can wait. 

No crashing occurs when searching for items, however, when searching for an item or group of items in the search bar no results show and nothing actually happens. This worked prior to JEI 3.13.3.365

Picture of Issue: http://tinypic.com/r/t65xc0/9

Minecraft: 1.10.2
Forge: 12.18.2.2125
JEI: 3.13.3.373
FEI: 1.0.17.2

**Comment by Elix-x** [comment]
And if you wait a while, does it still not show anything?

**Comment by DatrixTHLK** [comment]
Not exactly, when I exit out of the inventory screen and enter back into the inventory the item or group of items searched for disappears. It's as if I never typed anything in at all. All-in-All the short and simple answer is no.

**Comment by Elix-x** [comment]
That makes sense...
I mean i now know what's happening.
Will be fixed.

**Comment by DatrixTHLK** [comment]
Thanks for the response and the fix. =)

**Comment by 7OOTnegaTerces** [comment]
I believe I'm having the same issue, but with a few additional details that you may (or may not) find useful.  I've been using FEI 1.0.17.1 (with JEI 3.13.0.342) on Minecraft 1.10.2 for a while with no problems.  Today, however, when I upgraded to FEI 1.0.17.2 (with JEI 3.13.3.376), the search function froze.  That is, FEI filtered the list based on whatever had been in the search bar before I upgraded, and ignored future input to the search bar.  I could tell because not only did typing or deleting in the search bar produce no results, but whenever I exited the inventory screen and re-entered, the old search parameters were back in place.  I REALLY hope you fix this issue soon, as it is the only thing preventing me from finally using Refined Storage, which requires JEI JEI 3.13.0.348 or above.  Best wishes!

**Comment by DatrixTHLK** [comment]
That is basically what I said only in more of a descriptive sense.

**Comment by Elix-x** [comment]
@7OOTnegaTerces @DatrixTHLK Will be fixed with 1.1 for 1.11.

**Comment by DatrixTHLK** [comment]
Sounds good. Thanks again.

**Comment by 7OOTnegaTerces** [comment]
NOOOOO!!!! Okay, this I REALLY need fixed in 1.10.2!!!  I've a lot of mods, and it will be a WHILE before they all move up to 1.11.  Couldn't you do this one little fix?!?  PLEASE?!?

**Comment by Elix-x** [comment]
@7OOTnegaTerces Do you remember how fast mods moved from 1.9 to 1.10.2? Now multiple that time by 1.0000000000000000000000000000000000000000000000000000000001563 and that's exactly how much it will take mods to move to 1.11 ;).

It will probably will take more time for me for fixing this in 1.10.2, then for all of your mods moving to 1.11. But i'll see.

**Comment by 7OOTnegaTerces** [comment]
THANKS Elix-x!!! I don't have as much faith, but maybe I'm just overly pessimistic (or impatient, take your pick)...

**Comment by DatrixTHLK** [comment]
I feel your pain @7OOTnegaTerces I wonder if 1.11 can handle 1.10's mods...just like 1.9.4 mod's did for  1.10.2.

**Comment by DatrixTHLK** [comment]
Just out of curiosity @7OOTnegaTerces do you have EZStorage2? 

The reason I ask is because when I search for items using the search mode in EZStorage 2's Storage core it will work, but not in the FEI Search bar below. I had to click on the JEI Search Link in order for it to work and then type out my query, or the item searched for within the search bar in EZStorage's search function. Let me know if this works for you and if you have EZStorage 2. This is still FEI's issue anyway, but just wanted confirmation. 

If you don't have the mod installed, then don't worry about it as this is just a temporary workaround (albeit, not a very good one) I've found.

Picture of what I mean: 
![2016-12-14](https://cloud.githubusercontent.com/assets/13172036/21194977/d669b394-c1ff-11e6-9947-30efeeb1be5c.png)

**Comment by DatrixTHLK** [comment]
In a few days I'm going to head up to version 1.11. I want to see the new stuff it has. Can't stay stuck in the same version forever now can we? ;)

**Comment by Elix-x** [comment]
@DatrixTHLK I agree, but my TODO list kinda does not. I have 2 mods to finish updating to 1.11 as quickly as possible. Aaaand i have some other stuff that also has to be done better as fats as possible. Like editing & uploading something to youtube.

**Comment by 7OOTnegaTerces** [comment]
I that case, I think you might find this mod of great use: [CompatLayer](https://minecraft.curseforge.com/projects/compatlayer?gameCategorySlug=mc-mods&projectID=253729).  It makes the same mod capable of running on both 1.10 and 1.11 (provided you do a few formatting tasks)! I beg of you, please make use of this feature to make your latest versions backwards compatible with 1.10, I'm still waiting on many mods to update before I can make the shift, (though if they all start using CL, that could change in a hurry)!

**Comment by 7OOTnegaTerces** [comment]
Oh, and @DatrixTHLK, I'm not using EZStorage2, I'm using Refined Storage.

**Comment by Elix-x** [comment]
@7OOTnegaTerces FEI does not require almost any modifications. It's 1.1 features that take most of time. The other mod though, is not a mod that can be supported by compat layer in any way.

@7OOTnegaTerces @DatrixTHLK Also, i will be unable to make any of my 1.11 mods backwards compatible not due to mc or forge but due to some huge internal refactorings.

And BTW, Excore is already out for 1.11 😉 !

**Comment by 7OOTnegaTerces** [comment]
@Elix-x what other mod?!?

**Comment by Elix-x** [comment]
@7OOTnegaTerces Very simple to find: I'm not working on it alone and it also has a github repo.

**Comment by 7OOTnegaTerces** [comment]
You mean applied energistics?!?  Where did that come from?  When did we start talking about that mod?  I'm not even using it... (Refined Storage).

**Comment by Elix-x** [comment]
@7OOTnegaTerces Yup. That is the other mod that i'm trying to finish updating.

**Comment by DatrixTHLK** [comment]
I've tried Compat layer and it doesn't work, at least for the mods I use anyways. Also, it won't help with FEI and JEI, seeing as FEI isn't right since JEI updated. Thanks for the suggestion though. @7OOTnegaTerces 

@Elix-x I'm one of those people who don't mind if you don't make mods backwards compatible as I like to go to newer versions. I've already downloaded Excore in preping for FEI when it comes out for 1.11. Thanks for the update by the way. :)

In any case I'm in no hurry.

**Comment by DatrixTHLK** [comment]
I'm one of those people who don't mind if you don't make mods backwards compatible as I like to go to newer versions rather than staying stagnant in the same version for well over three years. I've already downloaded Excore in preping for FEI when it comes out for 1.11. Thanks for the update by the way.

**Comment by Elix-x** [comment]
@7OOTnegaTerces @DatrixTHLK [![1.1](https://i.imgur.com/Je20BuQ.png)](https://twitter.com/Elix_x_mc/status/812711830904680449)

**Comment by Elix-x** [comment]
@7OOTnegaTerces @DatrixTHLK [![1.1](https://i.imgur.com/Je20BuQ.png)](https://twitter.com/Elix_x_mc/status/812711830904680449)

**Comment by 7OOTnegaTerces** [comment]
See how infrequently FEI updates and how often it falls behind JEI (and I mean no criticism @Elix-x), I've stopped using it all together. Honestly, beyond built in button support for LLOR and MO, I really don't see what FEI does that JEI doesn't. Maybe I'm missing something, but if that's the case then obviously whatever that thing is it isn't anything I need or use. Sorry, but I really need to cut down on the number of mods I use so I don't have to spend so long waiting for the majority of them to update before I can.

**Comment by Elix-x** [comment]
@7OOTnegaTerces I completely understand you. Just to clarify, i'll quote "FEI adds what JEI didn't take from NEI". JEI only ported item list from NEI. FEI ports utilities grid (on top left) - buttons for switching gamemodes, time, weather, magnet mode... Inventory saves and mods list. These are less used features of NEI, so it's very possible you can live without them.

Infriquent updates? I can only confirm. All my code (not only for mods btw) has been in overhaul since end-october, without almost any updates or fixes. With that goes lost of interest, falling behind and even dying out.
My only untouched projects were non-java projects and AE.

**Comment by 7OOTnegaTerces** [comment]
@Elix-x Ah, well, JEI Buttons adds all of that stuff back save for the mod list at the top (and just what does that do anyway?) and buttons for LLOR and MO. And of those two, I only really used the buttons, which I can just assign to keys.

**Comment by Elix-x** [comment]
@7OOTnegaTerces Mods list lists all mods and items assigned to them.

Reminder: JEI Buttons came out a while after FEI. That should explain some of things.

**Comment by DatrixTHLK** [comment]
Just Enough Widgets aka Buttons came out after FEI did as well.
