### ISSUE TITLE
[Bug] Search bar does not work when manually typed

### ISSUE THREAD

**Issue by GazbonicAcid** [elix-x/Forever-Enough-Items#59]
When I manually type a search entry into the search bar it doesn't work at all.
Though the Item SubSets still works.
And backspacing the entry it makes clears the search.
But when I go to manually search by mod it doesn't work.
I am experiencing this is in my modpack.
[Township Farms version Dev_08-2016_12_04](https://www.atlauncher.com/pack/TownshipFarms/#7816)

**Comment by Elix-x** [comment]
Pretty sure this is also a bug introduced with me not catching up to JEI.

**Comment by majix560** [comment]
The thing about jei's cheat mode being used, seems I was premature in stating it.

**Comment by DatrixTHLK** [comment]
Just out of curiosity @majix560 do you have EZStorage2 in the specific modpack? The reason I ask is because when I search for items using the search mode in EZStorage 2's Storage core it will work, but not in the FEI Search bar below. I had to click on the JEI Search Link in order for it to work and then type out my query, or the item searched for within the search bar in EZStorage's search function. Let me know if this works for you and if you have EZStorage 2. This is still FEI's issue anyway, but just wanted confirmation.

Picture of what I mean: 
![2016-12-14](https://cloud.githubusercontent.com/assets/13172036/21194977/d669b394-c1ff-11e6-9947-30efeeb1be5c.png)

**Comment by GazbonicAcid** [comment]
No it isn't in the pack,
and even if it was it would only help when accessing an ez-storage system.
Which means that since I'm not adding it any way,
I still won't add it just to work around this issue.

**Comment by DatrixTHLK** [comment]
True. It only helps when accessing the system itself. It is a temporary work around until this mod updates again. I understand though. I don't like workarounds myself and would rather avoid it.  Anyways, only thing to do now is wait.

**Comment by Elix-x** [comment]
@DatrixTHLK @majix560 [![1.1](https://i.imgur.com/Je20BuQ.png)](https://twitter.com/Elix_x_mc/status/812711830904680449)

**Comment by GazbonicAcid** [comment]
If this fix is not for 1.10.2, I'm complaining.

**Comment by DatrixTHLK** [comment]
It isn't. Not that I know of...I'm not going to bother defending this mod author for his choices. It's his choice. If you want to complain go right ahead, but know that it will do you no good in the long run.

**Comment by Elix-x** [comment]
@majix560 Sadly no. And i'm unable to fix this in 1.10.2.
